### PR TITLE
Speed up the mock create time

### PR DESCRIPTION
**Pull request by rcgroot**
Regarding issue #124

### CODE REVIEW

**Comment by dflems** [comment]
@rcgroot: Have you benchmarked this? Is it comparable to the execution time before the copy was introduced?

**Comment by rcgroot** [comment]
The benchmark is not so accurate (it is the duration trend on our Jenkins continuous builds) but our compile-test-package-deploy-test job went from around 10 minutes to 20 minutes and back. Running the test target on developer machines saw similar changes.

But we run many tests which by default create many mocks in a default setUp().

**Comment by dflems** [comment]
@rcgroot: Thanks! We've got a similar setup. I'll give it a shot and see if it brings our numbers down.

**Comment by dflems** [comment]
@rcgroot: Update: This significantly reduced our combined test runtime from ~18m to ~8m. Also reduced some timeout flakiness that was happening as a result of the increased runtime. Nice find!

**Comment by jonreid** [comment]
THANK YOU!!

**Pull request merged**
